FROM ghcr.io/puppeteer/puppeteer:latest
USER root
ENV PUPPETEER_CACHE_DIR=/home/pptruser/.cache/puppeteer
WORKDIR /app
COPY package*.json tsconfig.json nodemon.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npx", "nodemon", "server.ts"]
